name: Build, Test & Lint

on:
  workflow_dispatch:
  pull_request:
    branches:
      - 'main'

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build_and_test:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Decrypt keystore props
      run: |
          echo "${{secrets.KEYSTORE_PROPS}}" > keystore.properties.asc
          gpg -d --passphrase "${{secrets.KEYSTORE_PASSWORD}}" --batch keystore.properties.asc > app/keystore.properties
    - name: Decrypt release key
      run: |
          echo "${{secrets.RELEASE_KEY}}" > key.jks.asc
          gpg -d --passphrase "${{secrets.KEYSTORE_PASSWORD}}" --batch key.jks.asc > app/key.jks
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'
        java-package: jdk

    - name: Run Unit Tests
      timeout-minutes: 10
      run: |
        ./gradlew testProductionReleaseUnitTest -continue --stacktrace --info
    - name: Upload Test Reports Folder App
      uses: actions/upload-artifact@v2

  lint:
    if: always()
    runs-on: ubuntu-latest
    needs: build_and_test
    steps:
      - uses: actions/checkout@v2
      - name: Decrypt keystore props
        run: |
          echo "${{secrets.KEYSTORE_PROPS}}" > keystore.properties.asc
          gpg -d --passphrase "${{secrets.KEYSTORE_PASSWORD}}" --batch keystore.properties.asc > app/keystore.properties
      - name: Decrypt release key
        run: |
          echo "${{secrets.RELEASE_KEY}}" > key.jks.asc
          gpg -d --passphrase "${{secrets.KEYSTORE_PASSWORD}}" --batch key.jks.asc > app/key.jks
      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: maxim-lobanov/setup-android-tools@v1
        with:
          packages: |
              platforms;android-30
          cache: true
      - name: Lint
        run: ./gradlew lintProductionDebug --continue
      
